clean up tools vs. scripts

diff --git a/next b/next
--- a/next
+++ b/next
@@ -1,12 +1,12 @@
 #!/bin/bash
 
 unset -v latest
-for file in scripts/next/*.go; do
+for file in tools/next/*.go; do
 	[[ $file -nt $latest ]] && latest=$file
 done
 
 if [ ! -f ./dist/next ] || [ $latest -nt ./dist/next ]; then
-	go build -o ./dist/next scripts/next/*.go || { echo 'failed to build next.go' ; exit 1; }
+	go build -o ./dist/next tools/next/*.go || { echo 'failed to build next.go' ; exit 1; }
 fi
 
 ./dist/next "$@"
diff --git a/next-old b/next-old
--- a/next-old
+++ b/next-old
@@ -1,12 +1,12 @@
 #!/bin/bash
 
 unset -v latest
-for file in scripts/next-old/*.go; do
+for file in tools/next-old/*.go; do
 	[[ $file -nt $latest ]] && latest=$file
 done
 
 if [ ! -f ./dist/next-old ] || [ $latest -nt ./dist/next-old ]; then
-	go build -o ./dist/next-old scripts/next-old/*.go || { echo 'failed to build next-old.go' ; exit 1; }
+	go build -o ./dist/next-old tools/next-old/*.go || { echo 'failed to build next-old.go' ; exit 1; }
 fi
 
 ./dist/next-old "$@"
