if run.go fails to build, don't processed forward executing ./dist/run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -7,7 +7,7 @@ done
 
 if [ ! -f ./dist/run ] || [ $latest -nt ./dist/run ]; then
 	mkdir -p ./dist
-	go build -o ./dist/run scripts/run/*.go
+	go build -o ./dist/run scripts/run/*.go || { echo 'failed to build run.go' ; exit 1; }
 fi
 
 ./dist/run "$@"
